"""initial_schema

Revision ID: 6e43d539df86
Revises:
Create Date: 2026-08-30 14:32:05.562728
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "6e43d539df86"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chapters",
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=80), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.CheckConstraint("number BETWEEN 1 AND 97", name="chapters_number_check"),
        sa.PrimaryKeyConstraint("number"),
        sa.UniqueConstraint("sort_order"),
    )
    op.create_table(
        "dataset_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column("daily_goal", sa.Integer(), nullable=False),
        sa.Column("direction", sa.String(length=24), nullable=False),
        sa.Column("input_mode", sa.String(length=16), nullable=False),
        sa.Column("selected_chapter", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "direction IN ('latin-deutsch', 'deutsch-latein', 'gemischt')",
            name="users_direction_check",
        ),
        sa.CheckConstraint("input_mode IN ('tippen', 'aufdecken')", name="users_input_mode_check"),
        sa.CheckConstraint("daily_goal BETWEEN 5 AND 50", name="users_daily_goal_check"),
        sa.CheckConstraint("email = lower(email)", name="users_email_normalized_check"),
        sa.CheckConstraint(
            "selected_chapter IS NULL OR selected_chapter BETWEEN 1 AND 97",
            name="users_selected_chapter_check",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "vocabulary",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("stable_key", sa.String(length=80), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("lesson", sa.Integer(), nullable=False),
        sa.Column("source_record", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=40), nullable=True),
        sa.Column("latin", sa.Text(), nullable=False),
        sa.Column("german", sa.Text(), nullable=False),
        sa.Column("feature", sa.Text(), nullable=True),
        sa.Column("part_of_speech", sa.Text(), nullable=True),
        sa.Column("grammar", sa.Text(), nullable=True),
        sa.Column("info", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("content_version", sa.Integer(), nullable=False),
        sa.CheckConstraint("lesson BETWEEN 1 AND 97", name="vocabulary_lesson_check"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sort_order"),
        sa.UniqueConstraint("stable_key"),
    )
    op.create_index("idx_vocabulary_lesson_id", "vocabulary", ["lesson", "id"], unique=False)
    op.create_index(op.f("ix_vocabulary_lesson"), "vocabulary", ["lesson"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_expires_at"), "sessions", ["expires_at"], unique=False)
    op.create_index(op.f("ix_sessions_token_hash"), "sessions", ["token_hash"], unique=True)
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "study_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("chapter", sa.Integer(), nullable=True),
        sa.Column("direction", sa.String(length=24), nullable=False),
        sa.Column("input_mode", sa.String(length=16), nullable=False),
        sa.Column("target_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "direction IN ('latin-deutsch', 'deutsch-latein', 'gemischt')",
            name="study_sessions_direction_check",
        ),
        sa.CheckConstraint(
            "input_mode IN ('tippen', 'aufdecken')", name="study_sessions_input_mode_check"
        ),
        sa.CheckConstraint(
            "chapter IS NULL OR chapter BETWEEN 1 AND 97", name="study_sessions_chapter_check"
        ),
        sa.CheckConstraint("target_count BETWEEN 1 AND 50", name="study_sessions_target_check"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_study_sessions_user_started", "study_sessions", ["user_id", "started_at"], unique=False
    )
    op.create_table(
        "user_favorites",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("vocabulary_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vocabulary_id"], ["vocabulary.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "vocabulary_id"),
    )
    op.create_table(
        "user_vocabulary_progress",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("vocabulary_id", sa.Uuid(), nullable=False),
        sa.Column("direction", sa.String(length=24), nullable=False),
        sa.Column("phase", sa.String(length=16), nullable=False),
        sa.Column("ease", sa.Float(), nullable=False),
        sa.Column("interval_days", sa.Float(), nullable=False),
        sa.Column("repetitions", sa.Integer(), nullable=False),
        sa.Column("lapses", sa.Integer(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_rating", sa.Integer(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "direction IN ('latin-deutsch', 'deutsch-latein')", name="progress_direction_check"
        ),
        sa.CheckConstraint(
            "phase IN ('learning', 'review', 'relearning')", name="progress_phase_check"
        ),
        sa.CheckConstraint("ease BETWEEN 1.3 AND 3.0", name="progress_ease_check"),
        sa.CheckConstraint("interval_days BETWEEN 0 AND 730", name="progress_interval_check"),
        sa.CheckConstraint("lapses >= 0", name="progress_lapses_check"),
        sa.CheckConstraint(
            "last_rating IS NULL OR last_rating BETWEEN 0 AND 3", name="progress_last_rating_check"
        ),
        sa.CheckConstraint("repetitions >= 0", name="progress_repetitions_check"),
        sa.CheckConstraint("version >= 0", name="progress_version_check"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vocabulary_id"], ["vocabulary.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "vocabulary_id", "direction"),
    )
    op.create_index(
        "idx_progress_user_due", "user_vocabulary_progress", ["user_id", "due_at"], unique=False
    )
    op.create_index(
        op.f("ix_user_vocabulary_progress_due_at"),
        "user_vocabulary_progress",
        ["due_at"],
        unique=False,
    )
    op.create_table(
        "study_session_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("vocabulary_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("direction", sa.String(length=24), nullable=False),
        sa.Column("base_version", sa.Integer(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revealed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checked_answer_hash", sa.String(length=64), nullable=True),
        sa.Column("checked_correct", sa.Boolean(), nullable=True),
        sa.CheckConstraint(
            "direction IN ('latin-deutsch', 'deutsch-latein')", name="study_items_direction_check"
        ),
        sa.CheckConstraint(
            "(checked_answer_hash IS NULL AND checked_correct IS NULL) OR "
            "(checked_answer_hash IS NOT NULL AND checked_correct IS NOT NULL)",
            name="study_items_check_result_consistent",
        ),
        sa.CheckConstraint("base_version >= 0", name="study_items_base_version_check"),
        sa.CheckConstraint("ordinal >= 1", name="study_items_ordinal_check"),
        sa.ForeignKeyConstraint(["session_id"], ["study_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vocabulary_id"], ["vocabulary.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "ordinal", name="uq_study_session_ordinal"),
        sa.UniqueConstraint(
            "session_id", "vocabulary_id", "direction", name="uq_study_session_card"
        ),
    )
    op.create_index(
        "idx_study_session_items_session",
        "study_session_items",
        ["session_id", "ordinal"],
        unique=False,
    )
    op.create_table(
        "review_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_item_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.Uuid(), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("vocabulary_id", sa.Uuid(), nullable=False),
        sa.Column("direction", sa.String(length=24), nullable=False),
        sa.Column("base_version", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=24), nullable=False),
        sa.Column("was_correct", sa.Boolean(), nullable=False),
        sa.Column("response_ms", sa.Integer(), nullable=True),
        sa.Column("answer", sa.String(length=250), nullable=True),
        sa.Column("next_due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("response_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "direction IN ('latin-deutsch', 'deutsch-latein')", name="reviews_direction_check"
        ),
        sa.CheckConstraint("mode IN ('typing', 'self_assessment')", name="reviews_mode_check"),
        sa.CheckConstraint("base_version >= 0", name="reviews_base_version_check"),
        sa.CheckConstraint("rating BETWEEN 0 AND 3", name="reviews_rating_check"),
        sa.CheckConstraint(
            "response_ms IS NULL OR response_ms BETWEEN 0 AND 600000",
            name="reviews_response_ms_check",
        ),
        sa.ForeignKeyConstraint(
            ["session_item_id"], ["study_session_items.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vocabulary_id"], ["vocabulary.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_item_id", name="uq_reviews_session_item"),
        sa.UniqueConstraint("user_id", "idempotency_key", name="uq_reviews_user_idempotency"),
        sa.UniqueConstraint(
            "user_id", "vocabulary_id", "direction", "base_version", name="uq_reviews_state_version"
        ),
    )
    op.create_index(
        "idx_reviews_user_created", "review_events", ["user_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_reviews_user_created", table_name="review_events")
    op.drop_table("review_events")
    op.drop_index("idx_study_session_items_session", table_name="study_session_items")
    op.drop_table("study_session_items")
    op.drop_index(op.f("ix_user_vocabulary_progress_due_at"), table_name="user_vocabulary_progress")
    op.drop_index("idx_progress_user_due", table_name="user_vocabulary_progress")
    op.drop_table("user_vocabulary_progress")
    op.drop_table("user_favorites")
    op.drop_index("idx_study_sessions_user_started", table_name="study_sessions")
    op.drop_table("study_sessions")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_token_hash"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_expires_at"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_vocabulary_lesson"), table_name="vocabulary")
    op.drop_index("idx_vocabulary_lesson_id", table_name="vocabulary")
    op.drop_table("vocabulary")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("dataset_versions")
    op.drop_table("chapters")
    # ### end Alembic commands ###
